services:
  facelocker-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: facelocker-backend
    container_name: facelocker-backend
    environment:
      DB_HOST: facelocker-database
      KEYCLOAK_BASE_URL: http://facelocker-keycloak:8080
    ports:
      - "$PORT:$PORT"
    depends_on:
      - facelocker-database
      - facelocker-keycloak
    env_file:
      - .env

  facelocker-database:
    build: postgres
    container_name: facelocker-database
    volumes:
    - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_MULTIPLE_DATABASES: $DB_DATABASE, keycloak
      TZ: "GMT"
      PGTZ: "GMT"
    ports:
      - "$DB_PORT:$DB_PORT"

  facelocker-keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: facelocker-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://facelocker-database/keycloak
      KC_DB_USERNAME: $DB_USERNAME
      KC_DB_PASSWORD: $DB_PASSWORD
      KEYCLOAK_ADMIN: $KEYCLOAK_ADMIN
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      KC_LOG_LEVEL: debug
      KC_LOG_CONSOLE_COLOR: "true"
      KC_LOG_CONSOLE_OUTPUT: default
    volumes:
      - ./keycloak/data:/opt/keycloak/data
      - ./keycloak/import:/opt/keycloak/data/import
    ports:
      - "$KEYCLOAK_PORT:8080"
    depends_on:
      - facelocker-database
    command:
      [
        "start-dev",
        "--import-realm",
        "--features=preview,admin-fine-grained-authz,token-exchange",
        "--spi-scripts-default-provider=default",
        "--spi-scripts-default-enabled=true",
        "--spi-authorization-policy-provider-js-enabled=true"
      ]
